### ISSUE TITLE
No currency for Netherlands Antilles or AN country code

### ISSUE THREAD

**Issue by jayPare** [thiagodp/country-to-currency#12]
Netherlands Antilles (AN or ANT country code) are not returning any currency.

**Comment by thiagodp** [comment]
@jayPare You are right. The package `country-list` does not return `AN` for `Netherlands Antilles`. I'll include it manually and release a new version that returns `ANG` (for `Netherlands Antillean Guilder`). Thanks for pointing it out.

**Comment by jayPare** [comment]
> @jayPare You are right. The package `country-list` does not return `AN` for `Netherlands Antilles`. I'll include it manually and release a new version that returns `ANG` (for `Netherlands Antillean Guilder`). Thanks for pointing it out.

I can create a PR if you want! :)

**Comment by thiagodp** [comment]
@jayPare Thx, I'm on it.
