### ISSUE TITLE
Currency for SV Country Code (El Salvador) should be USD

### ISSUE THREAD

**Issue by chaitanya-d** [thiagodp/country-to-currency#13]
El Salvador migrated to USD back in 2001: https://en.wikipedia.org/wiki/Salvadoran_col%C3%B3n#:~:text=The%20colon%20was%20the%20currency,the%20presidency%20of%20Francisco%20Flores.

Currently it returns SVC as result for this country

**Comment by thiagodp** [comment]
Thank you @chaitanya-d. I'll fix it.

**Comment by chaitanya-d** [comment]
Hi @thiagodp would you mind upgrading the version of the https://www.npmjs.com/package/country-to-currency?activeTab=readme with this fix? We are awaiting this update

**Comment by thiagodp** [comment]
Hi @chaitanya-d , no doubt. I forgot to publish it, sorry. 😅
Thank you.
