### ISSUE TITLE
Georgia vs. South Georgia

### ISSUE THREAD

**Issue by danielrentz** [thiagodp/country-to-currency#14]
Thanks for your helpful library!

I encountered a little bug. Region GS ([South Georgia and the South Sandwich Islands](https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands)) is a British overseas territory and unrelated to the country [Georgia](https://en.wikipedia.org/wiki/Georgia_(country)).

Here it incorrectly maps to GEL ([Georgian Lari](https://en.wikipedia.org/wiki/Georgian_lari)) but shoud map to either:
- FKP ([Falkland Islands pound](https://en.wikipedia.org/wiki/Falkland_Islands_pound)) according to the [South Georgia article](https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands),
- [GBP](https://en.wikipedia.org/wiki/Pound_sterling) according to the [article linked from there](https://en.wikipedia.org/wiki/Pound_sterling_in_the_South_Atlantic_and_the_Antarctic#South_Georgia_and_the_South_Sandwich_Islands), or the German article about [South Georgia](https://de.wikipedia.org/wiki/S%C3%BCdgeorgien_und_die_S%C3%BCdlichen_Sandwichinseln).

I think GBP would be more reasonable.

**Comment by thiagodp** [comment]
Done. Thank you @danielrentz
