### ISSUE TITLE
no union types for currency

### ISSUE THREAD

**Issue by reslear** [thiagodp/country-to-currency#15]
<img width="478" alt="Screenshot 2023-12-20 at 23 49 18" src="https://github.com/thiagodp/country-to-currency/assets/12596485/6dc86a03-de56-4992-89c1-0b24325be1d4">

**Comment by thiagodp** [comment]
Hello @reslear,

I'll add `as const` (TypeScript 3.4+) to the produced object so you can use union types like this:
```typescript
// Countries = "AD" | "AE" | "AF" ...
type Countries = keyof typeof countryToCurrency;
// Currencies = "EUR" | "AED" | "AFN" ...
type Currencies = typeof countryToCurrency[ Countries ];
```

**Comment by thiagodp** [comment]
I decided to add the new these types to the `1.1.0` [release](https://github.com/thiagodp/country-to-currency#typescript). Thank you
