### ISSUE TITLE
fix: `HR` (Croatia) to use `EUR` currency

### ISSUE THREAD

**Issue by jasongitmail** [thiagodp/country-to-currency#21]
From `HR: 'HUF',` (which is the Hungarian Forint and was supposed to be `HRK` for the Croatian Kuna) to `HR: 'EUR',`. 

HRK was replaced with Euro 2023-01-01 https://en.wikipedia.org/wiki/ISO_4217

**Comment by thiagodp** [comment]
I had fixed this in [1.0.7](https://github.com/thiagodp/country-to-currency/releases/tag/v1.0.7), but I incorrectly referenced Hungarian (`HU`) as `HR` in [1.1.1](https://github.com/thiagodp/country-to-currency/releases/tag/v1.1.1) and that introduced the error. Thanks @jasongitmail for pointing it out.
