### ISSUE TITLE
Consider: `SL: 'SLL',` -> `SL: 'SLE',`

### ISSUE THREAD

**Issue by jasongitmail** [thiagodp/country-to-currency#24]
This one is unclear, but it sounds like both are circulating in the country and they are transitioning to `SLE`. Using `SLE` would be more future proof in that case.

The [Wikipedia page for Sierra Leone](https://en.wikipedia.org/wiki/Sierra_Leone ) has the old Sierra Leone leon (SLL).

ChatGPT:

> "Sierra Leone uses two currency codes: SLL for the old Leone and SLE for the new Leone. In 2021, it was announced that a new 
Leone (SLE) would be introduced, worth 1,000 old Leones (SLL). This new Leone was introduced in July 2022, and both the old Leone (SLL) and new Leone (SLE) remained legal tender during the transition period. As of April 2023, both currencies were still in circulation, with the new Leone being the primary currency​​."
> 
> "Additionally, the European Union's Interinstitutional Style Guide confirms that Sierra Leone has two currencies in circulation, SLE and SLL, as part of the ISO 4217 codes. This reflects the ongoing transition from the old Leone to the new Leone, with both currencies being used simultaneously during the transition period​​."

**Comment by jasongitmail** [comment]
Thanks for maintaining this!

FWIW, I reviewed the entire [ISO 3166 countries list](https://en.wikipedia.org/wiki/ISO_3166-1) to review their currencies, using AI and again manually, and opened a few issues for updates.

The only remaining difference is that this country-to-currency list contains `AN`, for Netherlands Antilles, even though it was dissolved in 2010 and removed from ISO 3166-1, and the territories that made it up were added: BQ (Bonaire, Sint Eustatius, and Saba); CW (Curaçao); SX (Sint Maarten). 

That said, I think leaving `AN` in the list, as a special case makes sense for some years given that old devices (phones et al) could still be in use that have out of date OS's and that return `AN` for some time.

**Comment by thiagodp** [comment]
Thank you @jasongitmail for such a valuable contributions. 🙌

**Comment by thiagodp** [comment]
@jasongitmail I also [found this page](https://publications.europa.eu/code/en/en-5000700.htm#fn3) with this:
> The Sierra Leonean currency has been redenominated by removing three zeros from the denominations. A new currency code (SLE) represents the new valuation. During the transition period, from 1 July 2022 to 31 December 2023, both the old leone and the new leone will be in circulation.

The page can be useful for other fixes.

**Comment by jasongitmail** [comment]
> The Sierra Leonean currency has been redenominated by removing three zeros from the denominations. A new currency code (SLE) represents the new valuation. During the transition period, from 1 July 2022 to 31 December 2023, both the old leone and the new leone will be in circulation

Good find!
