### ISSUE TITLE
Add currency mapping for Kosovo XK

### ISSUE THREAD

**Issue by dukesilverr** [thiagodp/country-to-currency#26]
Hello,
We are resolving country based on a card BIN, and then using your lib trying to resolve a currency.
Just spotted that some cards provide an issuer country as `XK`, which is user assumed [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code for **Kosovo**.

Can we add it to the lib?
`XK -> EUR`, sources: https://economy-finance.ec.europa.eu/euro/use-euro/euro-outside-euro-area_en#whoelseusestheeuro, https://en.wikipedia.org/wiki/Kosovo#:~:text=The%20Euro%20is%20the%20official,RS%2DKM%20remains%20in%20use.

**Comment by thiagodp** [comment]
Hello, @dukesilverr !
Thank you, I'll release this change in the next version (soon). 

Just waiting for the NPM Registry maintenance... 😊

![image](https://github.com/user-attachments/assets/8cf47b5b-e6af-4cdb-b684-6a3fc42fed2d)

**Comment by thiagodp** [comment]
Included in [v2.0](https://github.com/thiagodp/country-to-currency/releases/tag/v2.0.0).

**Comment by dukesilverr** [comment]
Such a quick response, Kudos @thiagodp !
