### ISSUE TITLE
'KR' country code was incorrectly mapped.

### ISSUE THREAD

**Issue by MunjaeLee** [thiagodp/country-to-currency#5]
'KR' country code means that South Korea.
Currency code of South Korea is 'KRW' (https://en.wikipedia.org/wiki/ISO_4217)
But 'KR' country code was mapped 'KPW'. 
('KPW' means that North Korea.)

**Comment by thiagodp** [comment]
Hello, @MunjaeLee. Ok, I'll fix it soon. Thank you!

**Comment by MunjaeLee** [comment]
Hello @thiagodp. Thank you for quick fixing! It helped me a lot.
